
// Mock data for demo
export const MOCK_STORIES = [
  {
    id: 1,
    title: 'Pothole on Main Street',
    description: 'Large pothole causing traffic and vehicle damage',
    category: 'Roads',
    imageUrl: 'https://images.unsplash.com/photo-1594385404953-2e95f59bd115?w=800&auto=format&fit=crop',
    location: 'Main St & 5th Ave',
    timestamp: '2 hours ago',
    status: 'Reported',
    upvotes: 15,
    downvotes: 2,
    comments: 4,
  },
  {
    id: 2,
    title: 'Garbage Dump by River',
    description: 'Illegal garbage disposal near the river bank',
    category: 'Waste',
    imageUrl: 'https://images.unsplash.com/photo-1604187351574-c75ca79f5807?w=800&auto=format&fit=crop',
    location: 'Riverside Park',
    timestamp: '6 hours ago',
    status: 'Confirmed',
    upvotes: 32,
    downvotes: 1,
    comments: 8,
  },
  {
    id: 3,
    title: 'Broken Streetlight',
    description: 'Streetlight not working for past 3 days causing safety concerns',
    category: 'Electricity',
    imageUrl: 'https://images.unsplash.com/photo-1617419086536-43f92bf32362?w=800&auto=format&fit=crop',
    location: 'Oak Street',
    timestamp: '1 day ago',
    status: 'In Progress',
    upvotes: 21,
    downvotes: 0,
    comments: 5,
  },
  {
    id: 4,
    title: 'Water Leakage',
    description: 'Water pipe leakage causing water wastage',
    category: 'Water',
    imageUrl: 'https://images.unsplash.com/photo-1600500423642-ce421b78cf6c?w=800&auto=format&fit=crop',
    location: 'Pine Avenue',
    timestamp: '2 days ago',
    status: 'Resolved',
    upvotes: 45,
    downvotes: 3,
    comments: 12,
  },
  {
    id: 5,
    title: 'Damaged Park Bench',
    description: 'Wooden bench in city park is broken and needs repair',
    category: 'Parks',
    imageUrl: 'https://images.unsplash.com/photo-1588943211346-0908a1fb0b01?w=800&auto=format&fit=crop',
    location: 'Central Park',
    timestamp: '3 days ago',
    status: 'Confirmed',
    upvotes: 18,
    downvotes: 2,
    comments: 6,
  },
];
